import "dotenv/config";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { PrismaClient } from "@prisma/client";
import { emailMarkHtml } from "../lib/email";

// Shared helpers for the bug-handling scripts (CLAUDE.md "Bug handling",
// BL-009/010/011). Everything here targets the PRODUCTION database — bug
// reports only ever come from the live app (CLAUDE-CONCEPT.md §3).

export function bugsPrisma(): PrismaClient {
  const url = process.env.DATABASE_URL_PRODUCTION;
  if (!url) {
    console.error(
      "DATABASE_URL_PRODUCTION is not set. The bug-handling scripts operate on the production DB only — see CLAUDE.md."
    );
    process.exit(1);
  }
  return new PrismaClient({ datasources: { db: { url } } });
}

export type BugRow = {
  id: string;
  number: number;
  title: string;
  description: string;
  status: "OPEN" | "RESOLVED";
  screenshotUrl: string | null;
  reportedAt: Date;
  resolvedAt: Date | null;
  notifiedStartAt: Date | null;
  notifiedResolvedAt: Date | null;
  reporter: { email: string; name: string | null };
};

export const BUG_SELECT = {
  id: true,
  number: true,
  title: true,
  description: true,
  status: true,
  screenshotUrl: true,
  reportedAt: true,
  resolvedAt: true,
  notifiedStartAt: true,
  notifiedResolvedAt: true,
  reporter: { select: { email: true, name: true } },
} as const;

// Accept either the short `number` (e.g. "3") or the cuid `id`.
export async function resolveRef(prisma: PrismaClient, ref: string | undefined): Promise<BugRow | null> {
  if (!ref) return null;
  const where = /^\d+$/.test(ref) ? { number: Number(ref) } : { id: ref };
  return prisma.bugReport.findUnique({ where, select: BUG_SELECT }) as Promise<BugRow | null>;
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function reporterLabel(b: BugRow): string {
  return b.reporter.name ? `${b.reporter.name} <${b.reporter.email}>` : b.reporter.email;
}

// ── BUGS.md (BL-009) ──────────────────────────────────────────────────────
export async function regenerateBugsMd(prisma: PrismaClient): Promise<number> {
  const open = (await prisma.bugReport.findMany({
    where: { status: "OPEN" },
    orderBy: { number: "asc" },
    select: BUG_SELECT,
  })) as BugRow[];

  const lines: string[] = [
    "# Reported bugs (OPEN status)",
    "",
    "Generated by `npm run bugs:export` from the `OPEN` `BugReport` rows in the **production** database (`DATABASE_URL_PRODUCTION`). Not continuously synced — regenerate before starting bug work.",
    "",
    `_Last generated: ${new Date().toISOString()}_`,
    "",
  ];

  if (open.length === 0) {
    lines.push("No open bugs.");
  } else {
    for (const b of open) {
      lines.push(
        `## #${b.number} — ${b.title}`,
        "",
        `- **Reported:** ${isoDate(b.reportedAt)} by ${reporterLabel(b)}`,
        `- **Screenshot:** ${b.screenshotUrl ?? "—"}`,
        `- **id:** \`${b.id}\``,
        "",
        b.description.trim(),
        "",
        "---",
        ""
      );
    }
    lines.pop(); // trailing blank after last "---"
  }

  writeFileSync(join(process.cwd(), "BUGS.md"), lines.join("\n") + "\n");
  return open.length;
}

// ── SOLVED-BUGS.md (BL-011) ───────────────────────────────────────────────
const SOLVED_HEADER = `# Solved bugs (archive)

Append-only archive of resolved bugs — number, title, description, dates, and screenshot URL when present — written to when a \`BugReport\` is marked \`RESOLVED\` (see \`CLAUDE.md\`, "Bug handling").
`;

export function appendSolvedBugMd(b: BugRow): boolean {
  const path = join(process.cwd(), "SOLVED-BUGS.md");
  let current = existsSync(path) ? readFileSync(path, "utf8") : SOLVED_HEADER;

  // Drop the "No solved bugs yet." placeholder if it's still there.
  current = current.replace(/\n?No solved bugs yet\.\n?/g, "\n");
  if (current.includes(`## #${b.number} — `)) return false; // already archived

  const block = [
    "",
    "---",
    "",
    `## #${b.number} — ${b.title}`,
    "",
    `**Reported:** ${isoDate(b.reportedAt)} by ${reporterLabel(b)}`,
    `**Resolved:** ${isoDate(b.resolvedAt ?? new Date())}`,
    b.screenshotUrl ? `**Screenshot:** ${b.screenshotUrl}` : null,
    "",
    b.description.trim(),
    "",
  ]
    .filter((l) => l !== null)
    .join("\n");

  writeFileSync(path, current.replace(/\s*$/, "") + "\n" + block);
  return true;
}

// ── email templates ──────────────────────────────────────────────────────
const APP = "BarTender Track &amp; Trace Simulator";

export function startEmail(b: BugRow): { subject: string; html: string } {
  return {
    subject: `Bug #${b.number} is being worked on — ${b.title}`,
    html:
      emailMarkHtml() +
      `<p>Hi,</p>` +
      `<p>Your bug report <strong>#${b.number} — ${escapeHtml(b.title)}</strong> is now being worked on.</p>` +
      `<blockquote style="border-left:3px solid #ccc;margin:0;padding:0 0 0 12px;color:#555">${escapeHtml(
        b.description.slice(0, 400)
      )}</blockquote>` +
      `<p>We'll email you again once the fix is live. Thanks for reporting it.</p>` +
      `<p style="color:#888;font-size:12px">${APP}</p>`,
  };
}

export function resolvedEmail(b: BugRow): { subject: string; html: string } {
  return {
    subject: `Bug #${b.number} is fixed — ${b.title}`,
    html:
      emailMarkHtml() +
      `<p>Hi,</p>` +
      `<p>Your bug report <strong>#${b.number} — ${escapeHtml(b.title)}</strong> has been fixed and the change is live in production.</p>` +
      `<blockquote style="border-left:3px solid #ccc;margin:0;padding:0 0 0 12px;color:#555">${escapeHtml(
        b.description.slice(0, 400)
      )}</blockquote>` +
      `<p>Thanks for helping make the simulator better.</p>` +
      `<p style="color:#888;font-size:12px">${APP}</p>`,
  };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export { reporterLabel };
